services:
  - type: web
    name: hedamo-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, s-maxage=31536000
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 